language: php

php:
  - 7.0
#  - hhvm

addons:
  postgresql: "9.4"

before_install:
  - sudo apt-get update
  - sudo apt-get install language-pack-cs language-pack-ja
  - sudo /etc/init.d/postgresql stop
  - sudo sed -e 's~#\?max_prepared_transactions = 0~max_prepared_transactions = 1~' --in-place /etc/postgresql/9.4/main/postgresql.conf
  - sudo /etc/init.d/postgresql start 9.4
  - composer self-update

install:
  - composer install

before_script:
  - psql -c "CREATE USER ivory PASSWORD 'ivoryivory'" -U postgres
  - psql -c "CREATE DATABASE ivory_test OWNER ivory" -U postgres
  - cp test/phpunit.template.xml test/phpunit.xml
  - sed -e 's~\(name="DB_HOST" value="\).*\("\)~\1\2~' --in-place test/phpunit.xml
  - sed -e 's~\(name="DB_PORT" value="\).*\("\)~\1\2~' --in-place test/phpunit.xml
  - sed -e 's~\(name="DB_USER" value="\).*\("\)~\1ivory\2~' --in-place test/phpunit.xml
  - sed -e 's~\(name="DB_PASSWD" value="\).*\("\)~\1ivoryivory\2~' --in-place test/phpunit.xml
  - sed -e 's~\(name="DB_DBNAME" value="\).*\("\)~\1ivory_test\2~' --in-place test/phpunit.xml

script:
  - phpunit --bootstrap test/bootstrap.php --configuration test/phpunit.xml test/unit

