language: php

php:
  - '7.1'
  - '7.2'

env:
  - POSTGRESQL_VERSION=9.4
  - POSTGRESQL_VERSION=9.5
  - POSTGRESQL_VERSION=9.6
  - POSTGRESQL_VERSION=10

before_install:
  - sudo apt-get update
  - sudo apt-get install language-pack-cs language-pack-ja
  - sudo service postgresql stop
  - if [ "$POSTGRESQL_VERSION" -eq 10 ]; then sudo apt-get install -q postgresql-10 postgresql-client-10 && sudo cp /etc/postgresql/{9.6,10}/main/pg_hba.conf; fi
  - sudo sed -e 's~#\?max_prepared_transactions = 0~max_prepared_transactions = 1~' --in-place /etc/postgresql/$POSTGRESQL_VERSION/main/postgresql.conf
  - sudo service postgresql start $POSTGRESQL_VERSION
  - composer self-update

install:
  - composer install

before_script:
  - psql -c "CREATE USER ivory PASSWORD 'ivoryivory'" -U postgres
  - psql -c "CREATE DATABASE ivory_test OWNER ivory" -U postgres
  - cp test/phpunit.template.xml test/phpunit.xml
  - sed -e 's~\(name="DB_HOST" value="\).*\("\)~\1\2~' --in-place test/phpunit.xml
  - sed -e 's~\(name="DB_PORT" value="\).*\("\)~\1\2~' --in-place test/phpunit.xml
  - sed -e 's~\(name="DB_USER" value="\).*\("\)~\1ivory\2~' --in-place test/phpunit.xml
  - sed -e 's~\(name="DB_PASSWD" value="\).*\("\)~\1ivoryivory\2~' --in-place test/phpunit.xml
  - sed -e 's~\(name="DB_DBNAME" value="\).*\("\)~\1ivory_test\2~' --in-place test/phpunit.xml

script:
  - vendor/bin/phpunit --bootstrap test/bootstrap.php --configuration test/phpunit.xml test/unit

