language: php

php:
  - 5.6
  - nightly
#  - hhvm

addons:
  postgresql: 9.3

before_install:
  - composer self-update

install:
  - composer install

before_script:
  - psql -c 'create database ivory_test;' -U postgres

script:
  - phpunit --bootstrap test/bootstrap.php test/unit

